extends Node
class_name EnemyParameters

const DEFAULT_WANDER_SPEED = 300
const DEFAULT_CHASE_SPEED = 700
const DEFAULT_WANDER_TARGET_RANGE = 50
const DEFAULT_ATTACK_RANGE = 30
const DEFAULT_IDLE_TIMEOUT = 5
const DEFAULT_WANDER_TIMEOUT = 5
const DEFAULT_TIME_BETWEEN_ATTACKS = 1.5
const DEFAULT_CHASE_RANGE = 300

enum { WANDER_SPEED = 0, CHASE_SPEED, WANDER_TARGET_RANGE,
		ATTACK_RANGE, IDLE_TIMEOUT, WANDER_TIMEOUT, TIME_BETWEEN_ATTACKS,
		CHASE_RANGE, N_PARAMETERS}

var pars = []
func _init():
	pars.resize(N_PARAMETERS)
	pars[WANDER_SPEED] = DEFAULT_WANDER_SPEED
	pars[ATTACK_RANGE] = DEFAULT_ATTACK_RANGE
	pars[CHASE_SPEED] =  DEFAULT_CHASE_SPEED
	pars[WANDER_TARGET_RANGE] =  DEFAULT_WANDER_TARGET_RANGE
	pars[ATTACK_RANGE] = DEFAULT_ATTACK_RANGE
	pars[IDLE_TIMEOUT] = DEFAULT_IDLE_TIMEOUT
	pars[WANDER_TIMEOUT] = DEFAULT_WANDER_TIMEOUT
	pars[TIME_BETWEEN_ATTACKS] = DEFAULT_TIME_BETWEEN_ATTACKS
	pars[CHASE_RANGE] = DEFAULT_CHASE_RANGE

func get(index):
	return pars[index]

func set(index, value):
	pars[index] = value
